name: appwrite_flutter_tank_app_101125
description: "Tank App - Flutter Application"
publish_to: 'none'

version: 1.0.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  intl: ^0.20.2
  appwrite: ^14.0.0
  url_launcher: ^6.3.1
  window_manager: ^0.4.3
  cupertino_icons: ^1.0.8
  flutter_dotenv: ^6.0.0
  get: ^4.7.2
  geolocator: ^14.0.2
  http: ^1.6.0
  fl_chart: ^1.1.1
  device_info_plus: ^10.1.2

dependency_overrides:
  flutter_web_auth_2: 4.1.0

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.4.4
  flutter_launcher_icons: ^0.14.3

flutter:
  uses-material-design: true
  assets:
    - assets/
    - .env